<a href="https://colab.research.google.com/github/Maro94/wstep-do-ml-mariuszmallek19389B1-175ic/blob/main/zadanie1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np. full(10,5)


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
df = np.arange(10, 51, 1)
print(df)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
np.arange(0,9,1).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.normal(0, 0.5, (5,5))


array([[ 0.65018855,  0.19236638, -0.09374941,  0.61874164,  0.9244572 ],
       [-0.10900695,  0.20976078,  0.05216441,  0.28180249, -0.2036327 ],
       [ 0.91746368,  0.24239598, -0.26190319, -0.08940169, -0.92089492],
       [ 0.17559932, -0.32102443,  0.59214247, -0.0674766 ,  0.31004309],
       [ 0.47572363, -0.08958324, -0.68369601,  0.15776774, -0.32523987]])

In [ ]:
np.linspace(0.01, 1.0, 100).reshape(10, 10)


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.linspace(0, 1, 20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
df = np.random.randint(2, 25, 25).reshape(5, 5)
print(df)




[[ 4  4 14 16 15]
 [14 22 21  6 11]
 [23 21 15 12 15]
 [ 6 18 15 22  5]
 [23 20 11 23  2]]


In [ ]:
df.sum()

 

358

In [ ]:
df.mean()
 


14.32

In [ ]:
 
np.std(df)
df.sum(axis=0)


array([70, 85, 76, 79, 48])

In [ ]:
 
df.sum(axis=0)


array([70, 85, 76, 79, 48])

In [ ]:
df5x5 = np.random.randint(1, 100, (5, 5))
print(df5x5)


[[63 73 72 70 74]
 [90 46 26  1 33]
 [22 82 23 58 24]
 [58 22 55 97 70]
 [50 45 33 42 70]]


In [ ]:
np.median(df5x5)


55.0

In [ ]:
df5x5.min()


1

In [ ]:
df5x5.max()

97

In [ ]:
df = np.random.randint(1, 100, (4, 3))
print (df.T)


[[90 92 15 99]
 [64 24 84 88]
 [22 35 87 43]]


In [ ]:
df1 = np.random.random((4, 4))
df2 = np.random.random((4, 3))
print(df1)
print(df2)

[[0.44297654 0.7754974  0.87830228 0.16756945]
 [0.2157613  0.51615374 0.19189565 0.95700338]
 [0.81989862 0.10856336 0.15501352 0.75704875]
 [0.06033689 0.37646482 0.96325788 0.40072222]]
[[0.14678976 0.20477607 0.54200204]
 [0.2092748  0.78459334 0.41676122]
 [0.98819772 0.431996   0.6982105 ]
 [0.85318541 0.44701681 0.54046795]]


In [ ]:
df2 = np.append(df2, np.zeros((4, 1)), axis=1)
print(df2)

[[0.14678976 0.20477607 0.54200204 0.        ]
 [0.2092748  0.78459334 0.41676122 0.        ]
 [0.98819772 0.431996   0.6982105  0.        ]
 [0.85318541 0.44701681 0.54046795 0.        ]]


In [ ]:
print (df1 + df2)


[[0.5897663  0.98027347 1.42030432 0.16756945]
 [0.4250361  1.30074707 0.60865686 0.95700338]
 [1.80809634 0.54055936 0.85322402 0.75704875]
 [0.91352231 0.82348163 1.50372582 0.40072222]]


In [ ]:
mrandom1 = np.random.random((3, 4))
mrandom2 = np.random.random((4, 3))

print(mrandom1)
print(mrandom2)


[[0.71104243 0.56297028 0.22623514 0.15941252]
 [0.58268265 0.58774037 0.22626426 0.86571015]
 [0.55136919 0.87179152 0.14599701 0.68837092]]
[[0.81619648 0.3371685  0.88866072]
 [0.80376258 0.52714943 0.32675924]
 [0.56763552 0.61147497 0.9607011 ]
 [0.85861493 0.20697472 0.60111914]]


In [ ]:
print (np.matmul(mrandom1, mrandom2))
print (np.multiply(mrandom1.T, mrandom2))



[[1.29813784 0.70784206 1.12900147]
 [1.81973454 0.82382429 1.44762405]
 [1.82465764 0.87721762 1.3288985 ]]
[[0.58035033 0.19646223 0.48998014]
 [0.45249445 0.309827   0.28486593]
 [0.1284191  0.13835493 0.14025949]
 [0.13687397 0.17918012 0.41379293]]
